[project]
name = "voice-synthesizer"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sincro-config",
    "sincro-models",
    "redis[hiredis]>=6.4.0",
    "boto3>=1.42.14",
    "requests>=2.32.5",
    "pydantic>=2.11.7",
    "numpy==1.26.4",
    "uvicorn>=0.35.0",
    "fastapi>=0.116.1",
    "websockets>=15.0.1",
    "setproctitle>=1.3.6",
]

[tool.uv.sources]
sincro-config = { workspace = true }
sincro-models = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/voice_synthesizer"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
