include:
    - compose/initializer.yml
    - compose/frontend.yml
    - compose/sincro-rtc.yml
    - compose/speech-extractor.yml
    - compose/speech-recognizer.yml
    - compose/text-processor.yml
    - compose/voice-synthesizer.yml
    - compose/consul-server.yml
    - compose/s3.yml
    - compose/redis.yml
    # vrm360でLive配信を行いたい場合は、以下のコメントアウトを外す
    # - compose/mediamtx.yml

networks:
    sincromisor-net:
        ipam:
            config:
                - subnet: ${SINCRO_COMPOSE_NETWORK_SUBNET}
