services:
    service-initializer:
        profiles:
            - full
            - frontend
            - backend
        build:
            context: ..
            dockerfile: ./Docker/service-initializer/Dockerfile
        image: ${SINCRO_REGISTRY_NAME}/service-initializer
        environment:
            - SINCRO_S3_PUBLIC_BIND_HOST=${SINCRO_S3_PUBLIC_BIND_HOST}
            - SINCRO_S3_PUBLIC_BIND_PORT=${SINCRO_S3_PUBLIC_BIND_PORT}
            - SINCRO_S3_ACCESS_KEY=${SINCRO_S3_ACCESS_KEY}
            - SINCRO_S3_SECRET_KEY=${SINCRO_S3_SECRET_KEY}
            - SINCRO_RECOGNIZER_MODEL=${SINCRO_RECOGNIZER_MODEL}
        volumes:
            - ../volumes/sincro-cache:/opt/sincromisor/.cache
            - ../configs/config.yml:/opt/sincromisor/configs/config.yml:rw
        networks:
            - sincromisor-net
        depends_on:
            sincro-s3:
                condition: service_healthy

networks:
    sincromisor-net:
