services:
  sincro-mediamtx:
    logging: {driver: journald, options: {mode: non-blocking, max-buffer-size: "4m", labels: "com.docker.compose.project,com.docker.compose.service"}}
    profiles:
      - full
      - backend
      - external
    image: bluenviron/mediamtx:latest
    ports:
      - 1935:1935/tcp
    networks:
      - sincromisor-net
    deploy:
      restart_policy:
        condition: any
        delay: 10s

networks:
  sincromisor-net:
