include:
    - initializer.yml

services:
    sincro-rtc:
        profiles:
            - full
            - rtc
        build:
            context: ..
            dockerfile: ./Docker/sincro-rtc/Dockerfile
        image: ${SINCRO_REGISTRY_NAME}/sincro-rtc:latest
        command:
            [
                "--http",
                "0.0.0.0:8001",
                "--frontend-dir",
                "/opt/sincromisor/frontend",
                "--ffmpeg",
                "${SINCRO_PION_FFMPEG_PATH}",
                "--stun",
                "${SINCRO_PION_STUN}",
                "--media-udp-port",
                "${SINCRO_PION_MEDIA_UDP_PORT}",
                "--public-ipv4",
                "${SINCRO_PION_PUBLIC_IPV4}",
                "--interface",
                "${SINCRO_PION_INTERFACE}",
                "--max-sessions",
                "${SINCRO_RTC_MAX_SESSIONS}",
                "--consul-agent-host",
                "${SINCRO_PION_CONSUL_HTTP_HOST}",
                "--consul-agent-port",
                "${SINCRO_PION_CONSUL_HTTP_PORT}",
                "--service-bind-host",
                "${SINCRO_PION_SERVICE_BIND_HOST}",
            ]
        ports:
            - 8001:8001/tcp
            - ${SINCRO_PION_MEDIA_UDP_PORT}:${SINCRO_PION_MEDIA_UDP_PORT}/udp
        networks:
            - sincromisor-net
        depends_on:
            sincro-consul-server:
                condition: service_healthy
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "--fail",
                    "--silent",
                    "--show-error",
                    "http://127.0.0.1:8001/health/ready",
                ]
            interval: 10s
            timeout: 5s
            retries: 15

networks:
    sincromisor-net:
