#!/usr/bin/env node
/**
 * 各カテゴリの `<TASKS_ROOT>/<category>/index.md` 内の AUTOGEN ブロックを、
 * 配下タスクの `meta.yaml` から再生成する。
 *
 *   node scripts/tasks/genIndex.mjs           # 生成（差し替え）
 *   node scripts/tasks/genIndex.mjs --check    # 差分があれば exit 1（CI 用、書き込まない）
 *   bun  scripts/tasks/genIndex.mjs            # Bun でも同じ
 *
 * 既存 index.md の手書き前文（設計の出発点・各種設計表など）は温存し、
 * マーカー間のタスク一覧だけを差し替える。マーカーが無ければ末尾に追記する。
 */

import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
    discoverTasks,
    listDirs,
    mdCell,
    relLink,
    STATUSES,
    sortByStatusThenId,
    TASKS_ROOT,
} from "./lib.mjs";

const START =
    "<!-- AUTOGEN:tasks START — scripts/tasks/genIndex.mjs が再生成します。手で編集しないでください -->";
const END = "<!-- AUTOGEN:tasks END -->";
const LEGACY_START = "<!-- AUTOGEN:tasks START - generated by scripts/tasks/genIndex.mjs -->";

const STATUS_LABEL = {
    open: "open（未完）",
    blocked: "blocked（停止中）",
    done: "done（完了）",
    cancelled: "cancelled（取りやめ）",
    superseded: "superseded（廃止）",
};

function displayWidth(value) {
    let width = 0;
    for (const char of value) {
        const codePoint = char.codePointAt(0);
        const isWide =
            (codePoint >= 0x3000 && codePoint <= 0x9fff) ||
            (codePoint >= 0xff00 && codePoint <= 0xffef) ||
            codePoint >= 0x1f000 ||
            codePoint === 0x2705 ||
            codePoint === 0x274c;
        width += isWide ? 2 : 1;
    }
    return width;
}

function padDisplay(value, width) {
    return value + " ".repeat(Math.max(0, width - displayWidth(value)));
}

function renderTable(indexPath, tasks) {
    const rows = [["タスク", "タイトル", "判定", "依存"]];
    for (const t of tasks) {
        const link = relLink(indexPath, t.taskMdPath);
        const m = t.meta;
        const verdict = m.verdict ? (m.verdict === "PASS" ? "✅ PASS" : `❌ ${m.verdict}`) : "—";
        const deps = m.depends_on.length ? m.depends_on.map((d) => `\`${d}\``).join(", ") : "—";
        rows.push([`[${mdCell(m.id)}](${link})`, mdCell(m.title), verdict, mdCell(deps)]);
    }
    const widths = rows[0].map((_, column) =>
        Math.max(...rows.map((row) => displayWidth(row[column])), 3),
    );
    const renderRow = (row) =>
        `| ${row.map((cell, column) => padDisplay(cell, widths[column])).join(" | ")} |`;
    const separator = `| ${widths.map((width) => "-".repeat(Math.max(width, 3))).join(" | ")} |`;
    return [renderRow(rows[0]), separator, ...rows.slice(1).map(renderRow)].join("\n");
}

function renderBlock(indexPath, tasks) {
    const sorted = [...tasks].sort((a, b) => sortByStatusThenId(a.meta, b.meta));
    const sections = [];
    for (const status of STATUSES) {
        const inStatus = sorted.filter((t) => t.meta.status === status);
        if (inStatus.length === 0) continue;
        sections.push(
            `### ${STATUS_LABEL[status]} — ${inStatus.length} 件\n\n${renderTable(indexPath, inStatus)}`,
        );
    }
    const body = sections.length ? sections.join("\n\n") : "_(タスクなし)_";
    const total = sorted.length;
    return `${START}\n\n## タスク一覧（自動生成 / 全 ${total} 件）\n\n${body}\n\n${END}`;
}

/** 既存本文にブロックを差し込む。マーカーがあれば置換、無ければ末尾追記。 */
function spliceBlock(existing, category, block) {
    if (existing == null) {
        return `# ${category} タスク一覧\n\n${block}\n`;
    }
    const starts = [existing.indexOf(START), existing.indexOf(LEGACY_START)].filter((i) => i !== -1);
    const s = starts.length ? Math.min(...starts) : -1;
    const e = existing.lastIndexOf(END);
    if (s !== -1 && e !== -1 && e > s) {
        const before = existing.slice(0, s);
        const after = existing.slice(e + END.length);
        return `${before}${block}${after}`;
    }
    const trimmed = existing.replace(/\s+$/, "");
    return `${trimmed}\n\n${block}\n`;
}

async function main() {
    const check = process.argv.includes("--check");
    const tasks = await discoverTasks();
    const byCategory = new Map();
    for (const t of tasks) {
        const arr = byCategory.get(t.meta.category) ?? [];
        arr.push(t);
        byCategory.set(t.meta.category, arr);
    }

    // 既存の index.md があるカテゴリも拾う（タスクが 0 件になった場合に空表へ更新するため）
    for (const cat of await listDirs(TASKS_ROOT)) {
        if (existsSync(join(TASKS_ROOT, cat, "index.md")) && !byCategory.has(cat)) {
            byCategory.set(cat, []);
        }
    }

    let changed = 0;
    for (const [category, catTasks] of [...byCategory.entries()].sort()) {
        const indexPath = join(TASKS_ROOT, category, "index.md");
        const existing = existsSync(indexPath) ? await readFile(indexPath, "utf8") : null;
        const block = renderBlock(indexPath, catTasks);
        const next = spliceBlock(existing, category, block);
        if (next === existing) {
            console.log(`= ${indexPath} (変更なし, ${catTasks.length} 件)`);
            continue;
        }
        changed++;
        if (check) {
            console.log(`✗ ${indexPath} は最新ではありません（${catTasks.length} 件）`);
        } else {
            await writeFile(indexPath, next, "utf8");
            console.log(`✓ ${indexPath} を更新（${catTasks.length} 件）`);
        }
    }

    if (check && changed > 0) {
        console.error(
            `\n${changed} 件の index.md が古いです。\`tasks:index\` を実行してください。`,
        );
        process.exit(1);
    }
    console.log(`\n完了: ${byCategory.size} カテゴリ / ${tasks.length} タスク`);
}

await main();
