#!/usr/bin/env node

import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { discoverTasks, listDirs, mdCell, relLink, sortByStatusThenId, STATUSES, TASKS_ROOT } from "./lib.mjs";

const START = "<!-- AUTOGEN:tasks START - generated by scripts/tasks/genIndex.mjs -->";
const END = "<!-- AUTOGEN:tasks END -->";

const STATUS_LABELS = {
    open: "open",
    blocked: "blocked",
    done: "done",
    cancelled: "cancelled",
    superseded: "superseded",
};

function renderTable(indexPath, tasks) {
    const rows = [["Task", "Title", "Review", "Verdict", "Attempts", "Depends on"]];
    for (const task of tasks) {
        const meta = task.meta;
        const link = relLink(indexPath, task.taskMdPath);
        const review = meta.review ?? "-";
        const verdict = meta.verdict ?? "-";
        const attempts = String(meta.attempts);
        const dependsOn = meta.depends_on.length ? meta.depends_on.map((id) => `\`${id}\``).join(", ") : "-";
        rows.push([
            `[${mdCell(meta.id)}](${link})`,
            mdCell(meta.title),
            review,
            verdict,
            attempts,
            mdCell(dependsOn),
        ]);
    }

    const widths = rows[0].map((_, column) =>
        Math.max(...rows.map((row) => row[column].length), column === 0 ? 3 : 0),
    );
    const renderRow = (row) => `| ${row.map((cell, column) => cell.padEnd(widths[column])).join(" | ")} |`;
    const separator = `| ${widths.map((width) => "-".repeat(Math.max(width, 3))).join(" | ")} |`;
    return [renderRow(rows[0]), separator, ...rows.slice(1).map(renderRow)].join("\n");
}

function renderBlock(indexPath, tasks) {
    const sorted = [...tasks].sort((a, b) => sortByStatusThenId(a.meta, b.meta));
    const sections = [];
    for (const status of STATUSES) {
        const inStatus = sorted.filter((task) => task.meta.status === status);
        if (inStatus.length === 0) continue;
        sections.push(`### ${STATUS_LABELS[status]} (${inStatus.length})\n\n${renderTable(indexPath, inStatus)}`);
    }
    const body = sections.length ? sections.join("\n\n") : "_No tasks._";
    return `${START}\n\n## Task Index\n\n${body}\n\n${END}`;
}

function spliceBlock(existing, category, block) {
    if (existing == null) return `# ${category}\n\n${block}\n`;
    const start = existing.indexOf(START);
    const end = existing.indexOf(END);
    if (start !== -1 && end !== -1 && end > start) {
        return `${existing.slice(0, start)}${block}${existing.slice(end + END.length)}`;
    }
    return `${existing.replace(/\s+$/, "")}\n\n${block}\n`;
}

const check = process.argv.includes("--check");
const tasks = await discoverTasks();
const byCategory = new Map();

for (const task of tasks) {
    const categoryTasks = byCategory.get(task.meta.category) ?? [];
    categoryTasks.push(task);
    byCategory.set(task.meta.category, categoryTasks);
}

for (const category of await listDirs(TASKS_ROOT)) {
    if (existsSync(join(TASKS_ROOT, category, "index.md")) && !byCategory.has(category)) {
        byCategory.set(category, []);
    }
}

let changed = 0;
for (const [category, categoryTasks] of [...byCategory.entries()].sort()) {
    const indexPath = join(TASKS_ROOT, category, "index.md");
    const existing = existsSync(indexPath) ? await readFile(indexPath, "utf8") : null;
    const next = spliceBlock(existing, category, renderBlock(indexPath, categoryTasks));
    if (next === existing) {
        console.log(`= ${indexPath} (${categoryTasks.length} tasks)`);
        continue;
    }
    changed += 1;
    if (check) {
        console.log(`x ${indexPath} is stale (${categoryTasks.length} tasks)`);
    } else {
        await writeFile(indexPath, next, "utf8");
        console.log(`updated: ${indexPath} (${categoryTasks.length} tasks)`);
    }
}

if (check && changed > 0) {
    console.error(`${changed} index file(s) are stale. Run npm run tasks:index.`);
    process.exit(1);
}

console.log(`done: ${byCategory.size} categories, ${tasks.length} tasks`);
