[project]
name = "speech-recognizer"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "sincro-config",
    "sincro-models",
    "torch>=2.8.0",
    # 4.51.3: OK
    # 4.52.3: NG - AttributeError: 'GPTNeoXAttention' object has no attribute 'hidden_size'
    "transformers==4.51.3",
    "librosa>=0.11.0",
    "accelerate>=1.2.1",
    "deepspeed>=0.17.5",
    "sentencepiece>=0.2.1",
    "nue-asr @ git+https://github.com/rinnakk/nue-asr.git",
    "pydantic>=2.11.7",
    "numpy==1.26.4",
    "uvicorn>=0.35.0",
    "fastapi>=0.116.1",
    "websockets>=15.0.1",
    "setproctitle>=1.3.6",
    "boto3>=1.42.14",
]

[tool.uv.sources]
sincro-config = { workspace = true }
sincro-models = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/speech_recognizer"]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
