package pipeline

import (
	"bytes"
	"context"
	"errors"
	"io"
	"log/slog"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"reflect"
	"runtime"
	"strconv"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/coder/websocket"
	"github.com/vmihailenco/msgpack/v5"

	pclient "github.com/Sincromisor/Sincromisor/sincromisor-server/sincro-rtc-pion-poc/internal/pipeline/client"
	"github.com/Sincromisor/Sincromisor/sincromisor-server/sincro-rtc-pion-poc/internal/pipeline/discovery"
	"github.com/Sincromisor/Sincromisor/sincromisor-server/sincro-rtc-pion-poc/internal/pipeline/protocol"
)

type websocketFault string

const (
	faultNormal websocketFault = "normal"
	faultDecode websocketFault = "decode"
	faultRemote websocketFault = "remote"
)

// TestFixtureWebSocketPipeline exercises the actual production clients and codecs.
// Every server response starts from bytes generated by the Python fixture generator;
// the processor server patches only request identity/history that the coordinator owns.
func TestFixtureWebSocketPipeline(t *testing.T) {
	harness := newFixtureWebSocketHarness(t)
	defer harness.Close()
	coordinator, _ := newWebSocketCoordinator(t, harness)
	if err := coordinator.Start(context.Background(), "fixture-session", "sincro"); err != nil {
		t.Fatalf("Start() error = %v", err)
	}
	runWebSocketTurn(t, coordinator, 1)
	if harness.processorHistoryLength() != 1 {
		t.Fatalf("processor request history length = %d, want 1", harness.processorHistoryLength())
	}
	if harness.synthRequestCount() != 1 {
		t.Fatalf("synthesizer request count = %d, want 1", harness.synthRequestCount())
	}
	if err := coordinator.Close(); err != nil {
		t.Fatalf("Close() error = %v", err)
	}
	harness.waitActive(t, 0)
	harness.assertNoError(t)
}

func TestFixtureWebSocketResetMatrix(t *testing.T) {
	services := []pclient.Service{
		pclient.ServiceExtractor,
		pclient.ServiceRecognizer,
		pclient.ServiceProcessor,
		pclient.ServiceSynthesizer,
	}
	faults := []websocketFault{faultNormal, faultDecode, faultRemote}
	for _, service := range services {
		for _, fault := range faults {
			t.Run(string(service)+"/"+string(fault), func(t *testing.T) {
				harness := newFixtureWebSocketHarness(t)
				defer harness.Close()
				coordinator, waiter := newWebSocketCoordinator(t, harness)
				if err := coordinator.Start(context.Background(), "fixture-session", "sincro"); err != nil {
					t.Fatalf("Start() error = %v", err)
				}
				runWebSocketTurn(t, coordinator, 1)
				oldWork := transientWorkForTest(t, coordinator)
				seedTransientState(oldWork)
				if err := coordinator.publishText(
					1,
					pclient.ServiceProcessor,
					protocol.ChatMessage{SpeechID: 42, MessageID: "old-buffer"},
				); err != nil {
					t.Fatalf("publish old buffered output: %v", err)
				}
				beforeAccept := harness.acceptCounts()
				beforeSynth := harness.synthRequestCount()
				harness.resolver.failNextExtractor.Store(true)
				harness.fail(service, fault)
				waitForGeneration(t, coordinator, 2)

				if got := waiter.retryCount(); got != 1 {
					t.Fatalf("retry waiter count = %d, want 1", got)
				}
				if waiter.lastRetry() != RetryMin {
					t.Fatalf("retry delay = %v, want %v", waiter.lastRetry(), RetryMin)
				}
				harness.waitActive(t, 4)
				harness.assertAcceptedDelta(t, beforeAccept, 1)
				assertTransientReset(t, coordinator, oldWork)
				if len(coordinator.textOut) != 0 || len(coordinator.synthOut) != 0 {
					t.Fatalf("old output survived reset: text=%d synth=%d", len(coordinator.textOut), len(coordinator.synthOut))
				}
				if err := coordinator.publishText(
					1,
					pclient.ServiceProcessor,
					protocol.ChatMessage{SpeechID: 42, MessageID: "late"},
				); err != nil {
					t.Fatalf("publish stale output error = %v", err)
				}
				if len(coordinator.textOut) != 0 {
					t.Fatal("late generation-1 output reached external channel")
				}
				coordinator.mu.Lock()
				staleDrops := coordinator.staleDrops[pclient.ServiceProcessor]
				coordinator.mu.Unlock()
				if staleDrops != 1 {
					t.Fatalf("processor stale drop count = %d, want 1", staleDrops)
				}

				runWebSocketTurn(t, coordinator, 2)
				if harness.processorHistoryLength() != 3 {
					t.Fatalf("post-reset processor history length = %d, want 3", harness.processorHistoryLength())
				}
				if harness.synthRequestCount() != beforeSynth+1 {
					t.Fatalf("in-flight TTS was resent: synth count=%d want=%d",
						harness.synthRequestCount(), beforeSynth+1)
				}
				if err := coordinator.Close(); err != nil {
					t.Fatalf("Close() error = %v", err)
				}
				harness.waitActive(t, 0)
				harness.assertNoError(t)
			})
		}
	}
}

func TestFixtureWebSocketSimultaneousFailureAndRepeatedResetDoNotLeak(t *testing.T) {
	baseline := runtimeGoroutines()
	harness := newFixtureWebSocketHarness(t)
	defer harness.Close()
	coordinator, _ := newWebSocketCoordinator(t, harness)
	if err := coordinator.Start(context.Background(), "fixture-session", "sincro"); err != nil {
		t.Fatalf("Start() error = %v", err)
	}
	runWebSocketTurn(t, coordinator, 1)

	generation := uint64(1)
	for attempt := 0; attempt < 8; attempt++ {
		before := harness.acceptCounts()
		harness.fail(pclient.ServiceExtractor, faultRemote)
		harness.fail(pclient.ServiceProcessor, faultNormal)
		generation++
		waitForGeneration(t, coordinator, generation)
		harness.waitActive(t, 4)
		harness.assertAcceptedDelta(t, before, 1)
		if len(coordinator.textOut) != 0 || len(coordinator.synthOut) != 0 {
			t.Fatal("old generation output remained after repeated reset")
		}
	}
	if err := coordinator.Close(); err != nil {
		t.Fatalf("Close() error = %v", err)
	}
	harness.waitActive(t, 0)
	waitFor(t, func() bool { return runtimeGoroutines() <= baseline+5 })
	harness.assertNoError(t)
}

func runWebSocketTurn(t *testing.T, coordinator *Coordinator, generation uint64) {
	t.Helper()
	frame := make([]byte, pcmFrameBytes)
	if err := coordinator.SubmitPCM(frame); err != nil {
		t.Fatalf("SubmitPCM() error = %v", err)
	}
	user := receive(t, coordinator.TextResults())
	assistant := receive(t, coordinator.TextResults())
	voice := receive(t, coordinator.SynthResults())
	if user.Generation != generation || assistant.Generation != generation || voice.Generation != generation {
		t.Fatalf("turn output generations = %d/%d/%d, want %d",
			user.Generation, assistant.Generation, voice.Generation, generation)
	}
	if user.Value.Message != "固定文" || assistant.Value.Message != "固定された応答文" {
		t.Fatalf("fixture text outputs = %q / %q", user.Value.Message, assistant.Value.Message)
	}
	if !bytes.Equal(voice.Value.Voice, []byte("\x00\xffOggS\x00fixture")) {
		t.Fatalf("fixture synthesized voice = %x", voice.Value.Voice)
	}
}

func transientWorkForTest(t *testing.T, coordinator *Coordinator) *generationWork {
	t.Helper()
	coordinator.mu.Lock()
	defer coordinator.mu.Unlock()
	if coordinator.work == nil {
		t.Fatal("coordinator has no generation work")
	}
	return coordinator.work
}

func seedTransientState(work *generationWork) {
	work.conv.mu.Lock()
	work.conv.currentUser = &protocol.ChatMessage{SpeechID: 99, MessageID: "partial"}
	work.conv.requests[99] = protocol.ProcessorRequest{SessionID: "fixture-session", SequenceID: 99}
	work.conv.mu.Unlock()
}

func assertTransientReset(t *testing.T, coordinator *Coordinator, oldWork *generationWork) {
	t.Helper()
	coordinator.mu.Lock()
	newWork := coordinator.work
	coordinator.mu.Unlock()
	if newWork == nil || newWork == oldWork || newWork.conv == oldWork.conv || newWork.input == oldWork.input {
		t.Fatal("reset reused generation work, conversation, or input queue")
	}
	oldWork.input.mu.Lock()
	oldQueueClosed := oldWork.input.closed
	oldWork.input.mu.Unlock()
	if !oldQueueClosed {
		t.Fatal("reset did not close the old input queue")
	}
	newWork.conv.mu.Lock()
	defer newWork.conv.mu.Unlock()
	if newWork.conv.currentUser != nil || len(newWork.conv.requests) != 0 ||
		len(newWork.conv.outstanding) != 0 || len(newWork.conv.accumulated) != 0 {
		t.Fatal("new generation inherited transient conversation state")
	}
}

func waitForGeneration(t *testing.T, coordinator *Coordinator, generation uint64) {
	t.Helper()
	waitFor(t, func() bool {
		coordinator.mu.Lock()
		defer coordinator.mu.Unlock()
		return coordinator.state == StateRunning && coordinator.generation == generation
	})
}

type fixtureWebSocketHarness struct {
	t        *testing.T
	states   map[pclient.Service]*fixtureServiceState
	resolver *fixtureResolver
	fixtures map[string][]byte

	mu                 sync.Mutex
	processorHistories []int
	processorPayload   []byte
	synthRequests      int
	errs               []error
}

type fixtureServiceState struct {
	server   *httptest.Server
	mu       sync.Mutex
	conns    map[*websocket.Conn]struct{}
	accepted atomic.Int64
	active   atomic.Int64
}

func newFixtureWebSocketHarness(t *testing.T) *fixtureWebSocketHarness {
	t.Helper()
	harness := &fixtureWebSocketHarness{
		t:        t,
		states:   map[pclient.Service]*fixtureServiceState{},
		fixtures: map[string][]byte{},
	}
	for _, name := range []string{
		"extractor_initialize.msgpack",
		"extractor_result.msgpack",
		"recognizer_result.msgpack",
		"text_processor_request.msgpack",
		"text_processor_result.msgpack",
		"voice_synthesizer_result.msgpack",
	} {
		payload, err := os.ReadFile("protocol/testdata/" + name)
		if err != nil {
			t.Fatalf("read Python fixture %s: %v", name, err)
		}
		harness.fixtures[name] = payload
	}
	for _, service := range []pclient.Service{
		pclient.ServiceExtractor,
		pclient.ServiceRecognizer,
		pclient.ServiceProcessor,
		pclient.ServiceSynthesizer,
	} {
		state := &fixtureServiceState{conns: make(map[*websocket.Conn]struct{})}
		state.server = httptest.NewServer(http.HandlerFunc(func(
			response http.ResponseWriter,
			request *http.Request,
		) {
			harness.serve(service, state, response, request)
		}))
		harness.states[service] = state
	}
	harness.resolver = newFixtureResolver(t, harness.states)
	return harness
}

func (h *fixtureWebSocketHarness) serve(
	service pclient.Service,
	state *fixtureServiceState,
	response http.ResponseWriter,
	request *http.Request,
) {
	conn, err := websocket.Accept(response, request, nil)
	if err != nil {
		h.recordError(err)
		return
	}
	state.mu.Lock()
	state.conns[conn] = struct{}{}
	state.mu.Unlock()
	state.accepted.Add(1)
	state.active.Add(1)
	defer func() {
		_ = conn.CloseNow()
		state.mu.Lock()
		delete(state.conns, conn)
		state.mu.Unlock()
		state.active.Add(-1)
	}()

	ctx := request.Context()
	switch service {
	case pclient.ServiceExtractor:
		h.serveExtractor(ctx, conn)
	case pclient.ServiceRecognizer:
		h.serveRecognizer(ctx, conn)
	case pclient.ServiceProcessor:
		h.serveProcessor(ctx, conn)
	case pclient.ServiceSynthesizer:
		h.serveSynthesizer(ctx, conn)
	}
}

func (h *fixtureWebSocketHarness) serveExtractor(ctx context.Context, conn *websocket.Conn) {
	_, initialize, err := conn.Read(ctx)
	if err != nil {
		return
	}
	if !sameMessagePackKeys(initialize, h.fixtures["extractor_initialize.msgpack"]) {
		h.recordError(errors.New("extractor initialize does not match Python fixture schema"))
		return
	}
	for {
		_, _, err = conn.Read(ctx)
		if err != nil {
			return
		}
		if err = conn.Write(ctx, websocket.MessageBinary, h.fixtures["extractor_result.msgpack"]); err != nil {
			return
		}
	}
}

func (h *fixtureWebSocketHarness) serveRecognizer(ctx context.Context, conn *websocket.Conn) {
	fixture, err := protocol.DecodeExtractorResult(h.fixtures["extractor_result.msgpack"])
	if err != nil {
		h.recordError(err)
		return
	}
	for {
		_, payload, readErr := conn.Read(ctx)
		if readErr != nil {
			return
		}
		value, decodeErr := protocol.DecodeExtractorResult(payload)
		if decodeErr != nil || !reflect.DeepEqual(value, fixture) {
			h.recordError(errors.New("recognizer input differs from Python extractor fixture"))
			return
		}
		if err = conn.Write(ctx, websocket.MessageBinary, h.fixtures["recognizer_result.msgpack"]); err != nil {
			return
		}
	}
}

func (h *fixtureWebSocketHarness) serveProcessor(ctx context.Context, conn *websocket.Conn) {
	for {
		_, requestPayload, err := conn.Read(ctx)
		if err != nil {
			return
		}
		if !sameMessagePackKeys(requestPayload, h.fixtures["text_processor_request.msgpack"]) {
			h.recordError(errors.New("processor request does not match Python fixture schema"))
			return
		}
		responsePayload, historyLength, patchErr := h.processorResponse(requestPayload)
		if patchErr != nil {
			h.recordError(patchErr)
			return
		}
		h.mu.Lock()
		h.processorHistories = append(h.processorHistories, historyLength)
		h.processorPayload = append([]byte(nil), responsePayload...)
		h.mu.Unlock()
		if err = conn.Write(ctx, websocket.MessageBinary, responsePayload); err != nil {
			return
		}
	}
}

func (h *fixtureWebSocketHarness) processorResponse(requestPayload []byte) ([]byte, int, error) {
	var request map[string]any
	if err := msgpack.Unmarshal(requestPayload, &request); err != nil {
		return nil, 0, err
	}
	var response map[string]any
	if err := msgpack.Unmarshal(h.fixtures["text_processor_result.msgpack"], &response); err != nil {
		return nil, 0, err
	}
	requestHistory, ok := request["history"].(map[string]any)
	if !ok {
		return nil, 0, errors.New("processor request history is not a map")
	}
	messages, ok := requestHistory["messages"].([]any)
	if !ok {
		return nil, 0, errors.New("processor request history messages is not a list")
	}
	responseMessage, ok := response["response_message"].(map[string]any)
	if !ok {
		return nil, 0, errors.New("processor fixture response message is not a map")
	}
	requestMessage, ok := request["request_message"].(map[string]any)
	if !ok {
		return nil, 0, errors.New("processor request message is not a map")
	}
	responseMessage["speech_id"] = requestMessage["speech_id"]
	response["session_id"] = request["session_id"]
	response["sequence_id"] = request["sequence_id"]
	response["confirmed"] = request["confirmed"]
	response["request_message"] = requestMessage
	response["history"] = map[string]any{"messages": append(append([]any(nil), messages...), responseMessage)}
	response["end_of_response"] = true
	response["voice_text"] = "固定された応答文"
	payload, err := msgpack.Marshal(response)
	return payload, len(messages), err
}

func (h *fixtureWebSocketHarness) serveSynthesizer(ctx context.Context, conn *websocket.Conn) {
	for {
		_, payload, err := conn.Read(ctx)
		if err != nil {
			return
		}
		h.mu.Lock()
		expected := append([]byte(nil), h.processorPayload...)
		if !bytes.Equal(payload, expected) {
			h.errs = append(h.errs, errors.New("synthesizer did not receive raw processor fixture bytes"))
			h.mu.Unlock()
			return
		}
		h.synthRequests++
		h.mu.Unlock()
		if err = conn.Write(ctx, websocket.MessageBinary, h.fixtures["voice_synthesizer_result.msgpack"]); err != nil {
			return
		}
	}
}

func sameMessagePackKeys(actual, fixture []byte) bool {
	var actualMap, fixtureMap map[string]any
	if msgpack.Unmarshal(actual, &actualMap) != nil || msgpack.Unmarshal(fixture, &fixtureMap) != nil {
		return false
	}
	if len(actualMap) != len(fixtureMap) {
		return false
	}
	for key := range fixtureMap {
		if _, found := actualMap[key]; !found {
			return false
		}
	}
	return true
}

func (h *fixtureWebSocketHarness) fail(service pclient.Service, fault websocketFault) {
	state := h.states[service]
	state.mu.Lock()
	conns := make([]*websocket.Conn, 0, len(state.conns))
	for conn := range state.conns {
		conns = append(conns, conn)
	}
	state.mu.Unlock()
	for _, conn := range conns {
		switch fault {
		case faultDecode:
			_ = conn.Write(context.Background(), websocket.MessageBinary, []byte{0xc1})
		case faultNormal:
			go func(conn *websocket.Conn) {
				_ = conn.Close(websocket.StatusNormalClosure, "test normal close")
			}(conn)
		case faultRemote:
			go func(conn *websocket.Conn) {
				_ = conn.Close(websocket.StatusGoingAway, "test remote close")
			}(conn)
		}
	}
}

func (h *fixtureWebSocketHarness) acceptCounts() map[pclient.Service]int64 {
	result := make(map[pclient.Service]int64, len(h.states))
	for service, state := range h.states {
		result[service] = state.accepted.Load()
	}
	return result
}

func (h *fixtureWebSocketHarness) assertAcceptedDelta(
	t *testing.T,
	before map[pclient.Service]int64,
	delta int64,
) {
	t.Helper()
	for service, state := range h.states {
		if got := state.accepted.Load(); got != before[service]+delta {
			t.Fatalf("%s accepted count = %d, want %d", service, got, before[service]+delta)
		}
	}
}

func (h *fixtureWebSocketHarness) waitActive(t *testing.T, want int64) {
	t.Helper()
	waitFor(t, func() bool {
		var total int64
		for _, state := range h.states {
			total += state.active.Load()
		}
		return total == want
	})
}

func (h *fixtureWebSocketHarness) processorHistoryLength() int {
	h.mu.Lock()
	defer h.mu.Unlock()
	if len(h.processorHistories) == 0 {
		return -1
	}
	return h.processorHistories[len(h.processorHistories)-1]
}

func (h *fixtureWebSocketHarness) synthRequestCount() int {
	h.mu.Lock()
	defer h.mu.Unlock()
	return h.synthRequests
}

func (h *fixtureWebSocketHarness) recordError(err error) {
	h.mu.Lock()
	h.errs = append(h.errs, err)
	h.mu.Unlock()
}

func (h *fixtureWebSocketHarness) assertNoError(t *testing.T) {
	t.Helper()
	h.mu.Lock()
	defer h.mu.Unlock()
	if len(h.errs) > 0 {
		t.Fatalf("fixture WebSocket server errors: %v", h.errs)
	}
}

func (h *fixtureWebSocketHarness) Close() {
	for _, state := range h.states {
		state.mu.Lock()
		for conn := range state.conns {
			_ = conn.CloseNow()
		}
		state.mu.Unlock()
		state.server.Close()
	}
}

type fixtureResolver struct {
	endpoints         map[discovery.Service]discovery.Endpoint
	failNextExtractor atomic.Bool
}

func newFixtureResolver(t *testing.T, states map[pclient.Service]*fixtureServiceState) *fixtureResolver {
	t.Helper()
	result := &fixtureResolver{endpoints: make(map[discovery.Service]discovery.Endpoint)}
	for service, state := range states {
		host, portText, err := net.SplitHostPort(state.server.Listener.Addr().String())
		if err != nil {
			t.Fatalf("split fixture server address: %v", err)
		}
		port, err := strconv.Atoi(portText)
		if err != nil {
			t.Fatalf("parse fixture server port: %v", err)
		}
		result.endpoints[discovery.Service(service)] = discovery.Endpoint{
			Host: host, Port: uint16(port), Source: discovery.EndpointSourceConsul,
		}
	}
	return result
}

func (r *fixtureResolver) Resolve(
	_ context.Context,
	service discovery.Service,
) (discovery.Endpoint, error) {
	if service == discovery.ServiceExtractor && r.failNextExtractor.Swap(false) {
		return discovery.Endpoint{}, errors.New("injected reconnect resolve failure")
	}
	endpoint, found := r.endpoints[service]
	if !found {
		return discovery.Endpoint{}, errors.New("unknown fixture service")
	}
	return endpoint, nil
}

type integrationWaiter struct {
	mu      sync.Mutex
	retries []time.Duration
}

func (w *integrationWaiter) wait(ctx context.Context, delay time.Duration) <-chan error {
	if delay == outputBackpressure {
		result := make(chan error, 1)
		go func() {
			<-ctx.Done()
			result <- ctx.Err()
		}()
		return result
	}
	w.mu.Lock()
	w.retries = append(w.retries, delay)
	w.mu.Unlock()
	return immediateWait(ctx, delay)
}

func (w *integrationWaiter) retryCount() int {
	w.mu.Lock()
	defer w.mu.Unlock()
	return len(w.retries)
}

func (w *integrationWaiter) lastRetry() time.Duration {
	w.mu.Lock()
	defer w.mu.Unlock()
	if len(w.retries) == 0 {
		return 0
	}
	return w.retries[len(w.retries)-1]
}

func newWebSocketCoordinator(
	t *testing.T,
	harness *fixtureWebSocketHarness,
) (*Coordinator, *integrationWaiter) {
	t.Helper()
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	factory, err := pclient.NewSetFactory(harness.resolver, logger, func() time.Time {
		return time.Unix(1_700_000_000, 125_000_000)
	})
	if err != nil {
		t.Fatalf("NewSetFactory() error = %v", err)
	}
	waiter := &integrationWaiter{}
	coordinator, err := newCoordinatorWithHooks(
		factory,
		logger,
		func(cap time.Duration) (time.Duration, error) { return cap, nil },
		waiter.wait,
	)
	if err != nil {
		t.Fatalf("newCoordinatorWithHooks() error = %v", err)
	}
	return coordinator, waiter
}

func runtimeGoroutines() int {
	return runtime.NumGoroutine()
}
